#!/usr/bin/env ruby

require 'net/http'

PATFT_DOMAIN = "patft.uspto.gov"

RESOURCE = "/netacgi/nph-Parser?"

QUERY_STRING = <<-EOS.gsub(/\s*/, '') 
  Sect1=PTO1&
  Sect2=HITOFF&
  d=PALL&
  p=1&
  u=%%2Fnetahtml%%2FPTO%%2Fsrchnum.htm&
  r=1&
  f=G&
  l=50&
  s1=%{n}.PN.&
  OS=PN/%{n}&
  RS=PN/%{n}
EOS

patents = ARGF.read.split(/\R/)

def build_url(number)
  RESOURCE + sprintf(QUERY_STRING, n: number)
end

def get(domain, resource)
  Net::HTTP.get(domain, resource).gsub(/\R/, '')
end

def download(number)
  get(PATFT_DOMAIN, build_url(number))
end

patents.each_with_index do |p, index|
  $stdout.print(download(p), "\n")
end
