#!/usr/bin/env ruby

require 'net/http'

PATFT_URL = "http://patft.uspto.gov/netacgi/nph-Parser?"

PATFT_QUERY_STRING = <<-EOS.gsub(/\s*/, '') 
  Sect1=PTO1&
  Sect2=HITOFF&
  d=PALL&
  p=1&
  u=%%2Fnetahtml%%2FPTO%%2Fsrchnum.htm&
  r=1&
  f=G&
  l=50&
  s1=%{n}.PN.&
  OS=PN/%{n}&
  RS=PN/%{n}
EOS

patents = ARGF.read.split(/\R/)

def build_url(number)
  URI(PATFT_URL + sprintf(PATFT_QUERY_STRING, n: number))
end

def get(url)
  Net::HTTP.get(url).gsub(/\R/, '')
end

def download(number)
  get(build_url(number))
end

patents.each_with_index do |number, index|
  $stdout.print(download(number), "\n")
  # $stdout.print("Hello")
end
